In [1]:
import numpy as np

In [2]:
arr = np.arange(0,30,3)

In [3]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
arr[3]

9

In [7]:
arr[2:5]

array([ 6,  9, 12])

In [8]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [9]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [10]:
arr[2:] = 100

In [11]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

ARRAYS BIDIMENSIONAIS

In [14]:
arr = np.arange(50).reshape((5,10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

array de 5 linhas, por 10 colunas:

In [16]:
arr.shape

(5, 10)

primeiro colchete faz menção as linhas e segundo para as colunas:

In [17]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [18]:
arr2 = arr[:3]

In [19]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [20]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [21]:
arr2[:] = 100

In [22]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [23]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [24]:
arr2 = arr[:3].copy()

In [25]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [26]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

Parâmetro de fatiamento em um só colchete

In [28]:
arr[1:4,5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [30]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

lÊ-se: quando meu array é maior que 50? ele retorna valores,
    boleanos

In [31]:
arr > 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [32]:
bol = arr > 50

In [33]:
arr[bol]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [36]:
array = np.linspace(0,100, 30)

In [37]:
array

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

o método shape devolve a quantidade de elementos do array

In [38]:
array.shape

(30,)

In [39]:
array = array.reshape(3,10)

agora é array de 2 dimensões: 

In [40]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [41]:
array.shape

(3, 10)

In [42]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [43]:
array[0:2, 2]

array([ 6.89655172, 41.37931034])