In [3]:
import numpy as np

In [4]:
minha_lista = [1, 2, 3]

In [5]:
minha_lista

[1, 2, 3]

In [6]:
np.array(minha_lista)

array([1, 2, 3])

In [8]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
arr = np.zeros((5,5))

In [15]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.linspace(0,10, 2)

array([ 0., 10.])

In [22]:
np.random.rand(5)

array([0.53564743, 0.41363175, 0.87297749, 0.36296389, 0.08263855])

In [23]:
np.random.rand(5)*100

array([53.82658781, 69.52230123, 12.95775051, 45.00414946, 52.62886128])

In [25]:
np.random.rand(5, 4, 3)

array([[[0.14402903, 0.96293146, 0.48108775],
        [0.38065268, 0.90551216, 0.72911901],
        [0.98348024, 0.9195174 , 0.88228762],
        [0.49812687, 0.87766884, 0.73919157]],

       [[0.30621311, 0.37629789, 0.36452888],
        [0.41517761, 0.94811374, 0.66378857],
        [0.80187762, 0.67387223, 0.84861413],
        [0.36714543, 0.19876671, 0.40348505]],

       [[0.10509825, 0.67623006, 0.66713508],
        [0.48435596, 0.99026384, 0.66688952],
        [0.20378739, 0.91404729, 0.72291283],
        [0.74828053, 0.06632984, 0.52567726]],

       [[0.6370997 , 0.1737152 , 0.75619763],
        [0.06709724, 0.73586191, 0.30762645],
        [0.13159203, 0.14709029, 0.15107083],
        [0.57591883, 0.85783651, 0.08446585]],

       [[0.75296964, 0.9681611 , 0.21494377],
        [0.64840517, 0.70826876, 0.98406748],
        [0.56420322, 0.56238468, 0.27162445],
        [0.16401464, 0.83099753, 0.40381488]]])

In [26]:
np.random.randn(4)

array([-0.662874  , -0.44594303,  0.89335155,  0.65801519])

In [28]:
np.random.randint(0,100,10)

array([94, 91, 27, 21, 76, 21, 24, 41, 95, 38])

In [31]:
np.round(np.random.rand(5)*100, 0)

array([ 8., 68., 96., 74., 68.])

In [32]:
arr = np.random.rand(25)

In [33]:
arr

array([0.62357884, 0.11848108, 0.63608777, 0.95099814, 0.13955411,
       0.88117682, 0.03792559, 0.46934222, 0.51098488, 0.58281759,
       0.48916356, 0.50122446, 0.94299675, 0.79358853, 0.45287704,
       0.35322136, 0.99564753, 0.92884118, 0.42636798, 0.86261882,
       0.83115748, 0.96051479, 0.44667751, 0.26080854, 0.08875045])

In [34]:
arr.reshape(5,5)

array([[0.62357884, 0.11848108, 0.63608777, 0.95099814, 0.13955411],
       [0.88117682, 0.03792559, 0.46934222, 0.51098488, 0.58281759],
       [0.48916356, 0.50122446, 0.94299675, 0.79358853, 0.45287704],
       [0.35322136, 0.99564753, 0.92884118, 0.42636798, 0.86261882],
       [0.83115748, 0.96051479, 0.44667751, 0.26080854, 0.08875045]])

In [35]:
arr

array([0.62357884, 0.11848108, 0.63608777, 0.95099814, 0.13955411,
       0.88117682, 0.03792559, 0.46934222, 0.51098488, 0.58281759,
       0.48916356, 0.50122446, 0.94299675, 0.79358853, 0.45287704,
       0.35322136, 0.99564753, 0.92884118, 0.42636798, 0.86261882,
       0.83115748, 0.96051479, 0.44667751, 0.26080854, 0.08875045])

In [36]:
arr = arr.reshape((5,5))

In [37]:
arr

array([[0.62357884, 0.11848108, 0.63608777, 0.95099814, 0.13955411],
       [0.88117682, 0.03792559, 0.46934222, 0.51098488, 0.58281759],
       [0.48916356, 0.50122446, 0.94299675, 0.79358853, 0.45287704],
       [0.35322136, 0.99564753, 0.92884118, 0.42636798, 0.86261882],
       [0.83115748, 0.96051479, 0.44667751, 0.26080854, 0.08875045]])

In [38]:
arr.shape

(5, 5)

In [40]:
arr.max()

0.9956475329414191

In [41]:
arr.min()

0.0379255859934694

In [42]:
arr.argmax()

16

In [43]:
arr.argmin()

6